app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

users:
    type:     rest
    resource: AppBundle\Controller\UsersController
