app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin


# API

users:
    type: rest
    prefix: /api
    resource: AppBundle\Controller\UsersController


events:
    type: rest
    prefix: /api
    resource: AppBundle\Controller\EventController

bills:
    type: rest
    prefix: /api
    resource: AppBundle\Controller\BillController

