<?php

namespace AppBundle\Entity;

/**
 * CircleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CircleRepository extends \Doctrine\ORM\EntityRepository
{
}
